/**
 * @file layout.tsx
 * @author
 * Xuan Tuan Minh Nguyen, Trong Dat Hoang, Henry Nguyen
 * @description Root layout component for the Next.js application, including global styles, fonts, and essential setup.
 */

import type { Metadata } from "next";
// Import local fonts
import localFont from "next/font/local";
// Import global CSS styles
import "./globals.css";
// Import UI components and utilities
import { Toaster } from "@/components/ui/sonner";
import { revalidatePath, unstable_noStore } from "next/cache";

// Load the Geist Sans variable font with specified weights
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
// Load the Geist Mono variable font with specified weights
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata for the application, used by Next.js for SEO
export const metadata: Metadata = {
  title: "AviAI",
  description: "Generated by create next app",
};

// Define the root layout component, which wraps around all pages
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Instruct Next.js not to cache this layout
  unstable_noStore();
  // Revalidate the root path to ensure fresh data
  revalidatePath("/");
  // Return the HTML structure of the page
  return (
    <html lang="en">
      <body
        // Apply loaded fonts and antialiasing for smoother text
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the child components (pages) */}
        {children}
        {/* Include the Toaster component for displaying notifications */}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
